### ISSUE TITLE
[Feature] Card background as default as HA

### ISSUE THREAD

**Issue by poudenes** [eyalgal/ha-shopping-list-card#2]
Hi,

I love the card!! Is there a way to have the background color as default instead of white?

Greets,
Peter

**Comment by eyalgal** [comment]
Hey @poudenes, thanks so much for the feedback and the great suggestion! I completely agree, that's a much better user experience.

I'm happy to let you know that this feature has been implemented and is available as part of the new [v1.2.0 release](https://github.com/eyalgal/ha-shopping-list-card/releases/tag/v1.2.0)!

All you need to do is update the card in HACS to the latest version, and this will be the new default behavior.

Thanks again for helping make the card better for everyone! I'll go ahead and close this issue now. Cheers!

**Comment by poudenes** [comment]
Hey,

After updating i don't see the change. Even with browser refresh.

**Comment by eyalgal** [comment]
After updating, your browser might still be using cached files. To fully refresh:

Open Dev Tools (F12) → right-click the refresh button → select "Empty Cache and Hard Reload".
This forces the browser to load the latest version of the card. Let me know if it works!

**Comment by poudenes** [comment]
Didn't help. Even using Brave Browser on MacOS didnt help.

On the left how all my cards look like. Little transparant. On the right the shopping cards

<img width="1018" alt="Image" src="https://github.com/user-attachments/assets/3862dfe0-f141-4786-b428-842909d27677" />

Even after update to 1.3.0 it didn't solve.

```
type: vertical-stack
cards:
  - type: vertical-stack
    title: Boodschappen
    cards:
      - type: custom:shopping-list-card
        title: Drinken
        todo_list: todo.albert_heijn
        off_icon: mdi:basket-check
        on_icon: mdi:basket
        off_color: red
        enable_quantity: true
        colorize_background: false
      - type: custom:shopping-list-card
        title: Aardbeien
        todo_list: todo.albert_heijn
        enable_quantity: true
        off_icon: mdi:basket-check
        on_icon: mdi:basket
        off_color: red
        colorize_background: false
```
